### ISSUE TITLE
Error in query method

### ISSUE THREAD

**Issue by michilu** [soundTricker/SpreadsheetDB-For-Google_Apps_Script#6]
spreadsheetService.query(sheetName, keyword)で一致する行がないと「に対するリクエストに失敗し、コード 400 が返されました。サーバーの応答: 解析エラー: Invalid token encountered (line 303)」エラーになります。

なにも考慮しないとscriptが終了してしまいます。
何かよいハンドリング方法はありますか？

**Comment by soundTricker** [comment]
@MiCHiLU 
少し見てみるので少々お待ち下さい。

**Comment by soundTricker** [comment]
@MiCHiLU 
一致する行がない場合は空のArrayが返却されるはずです。

Error Codeの通り、keywordの部分が解析できなくてエラーになっているように思います。

どういったkeywordを投げていますか？？

**Comment by soundTricker** [comment]
@MiCHiLU 
ちなみにですが、keywordで`"name=sound tricker"`の様にスペース(または@、- それ以外にもあるかもしれません)を含む場合はSpreadsheet List APIの仕様でエラーとなります。

こういった場合は`"name=\"sound tricker\""`の様にダブルクォートで括る必要があります。

**Comment by michilu** [comment]
keywordは、 `国=台湾（北部地域）及び中国南部沿岸地域` でした。
ご指摘いただいたとおり `国="台湾（北部地域）及び中国南部沿岸地域"` と括ったところエラーが起こりませんでした。
ありがとうございます！

**Comment by soundTricker** [comment]
@MiCHiLU

良かったです！
使って頂いてありがとうございます
ドキュメントにも反映しておきますね
